### PR TITLE
Fix Excel false leapyear issue

### PR DESCRIPTION
**Pull request by jmcnamara**
Fix issue where Excel treats 1900 as a leapyear and add an
extra day.

Issue #58

### CODE REVIEW

**Comment by jeroen** [comment]
Thank you

**Comment by jmcnamara** [comment]
After doing some more testing the solution is incorrect for hours on 1900/02/28. The solution should be (relative to master):

```diff
diff --git a/src/write_xlsx.c b/src/write_xlsx.c
index 4a3c15b..afb0656 100644
--- a/src/write_xlsx.c
+++ b/src/write_xlsx.c
@@ -155,7 +155,7 @@ SEXP C_write_data_frame_list(SEXP df_list, SEXP file, SEXP col_names, SEXP forma
           double val = REAL(col)[i];
           if(R_FINITE(val))
             val = 25568.0 + val / (24*60*60);
-            if(val > 59.0)
+            if(val >= 60.0)
               val = val + 1.0;
             assert_lxw(worksheet_write_number(sheet, cursor, j, val , NULL));
         }; continue;
```

Note, I'm adding a function to libxlsxwriter to do this conversion directly (and with unit tests) so that you, and other users, will be able to avoid issues like this in the future.

I can submit another PR if you wish.

**Comment by jeroen** [comment]
OK sounds good

**Comment by jeroen** [comment]
Sorry for the late comment, but did you intend to put parentheses around this block as fixed in https://github.com/ropensci/writexl/commit/876b74de87c79b763c4bea5b0f3e53cbfe71f548 ?

**Comment by jmcnamara** [comment]
> Sorry for the late comment, but did you intend to put parentheses around this block as fixed in [876b74d](https://github.com/ropensci/writexl/commit/876b74de87c79b763c4bea5b0f3e53cbfe71f548) ?

Yes. Apologies. That was a bad miss on my part.

**Pull request merged**
